/*
 * Definiciones.h
 *
 *  Created on: 21 abr. 2017
 *      Author: julieta
 */

#ifndef DEFINICIONES_H_
#define DEFINICIONES_H_

#define ANIMACION_QUIETO_DERECHA 	"AqD"
#define ANIMACION_CAMINAR_DERECHA 	"AcD"
#define ANIMACION_CORRER_DERECHA 	"AxD"
#define ANIMACION_SALTAR_DERECHA 	"AsD"

#define ANIMACION_QUIETO_IZQUIERDA 	"AqI"
#define ANIMACION_CAMINAR_IZQUIERDA "AcI"
#define ANIMACION_CORRER_IZQUIERDA 	"AxI"
#define ANIMACION_SALTAR_IZQUIERDA 	"AsI"

#define TECLA_ARRIBA_PRESIONADA 	"TuP"
#define TECLA_ABAJO_PRESIONADA 		"TdP"
#define TECLA_DERECHA_PRESIONADA 	"TrP"
#define TECLA_IZQUIERDA_PRESIONADA 	"TlP"
#define TECLA_CORRER_PRESIONADA 	"TcP"

#define TECLA_ARRIBA_LIBERADA	 	"TuL"
#define TECLA_ABAJO_LIBERADA 		"TdL"
#define TECLA_DERECHA_LIBERADA 		"TrL"
#define TECLA_IZQUIERDA_LIBERADA 	"TlL"
#define TECLA_CORRER_LIBERADA	 	"TcL"

#define MENSAJE_CAMARA				"CAM"
#define MENSAJE_POSICION			"POS"

#define PADDING 						'-'
#define MAX_CANT_DIGITOS_POS 			4
#define LARGO_MENSAJE_POSICION_CLIENTE 	30
#define LARGO_MENSAJE_POSICION_SERVIDOR 15
#endif
